export const servicesData = [
  {
    name: 'Odontología General',
    slug: 'odontologia-general',
    description: 'Diagnóstico, prevención y tratamiento integral de la salud oral. Incluye limpiezas profesionales, restauraciones, tratamientos de caries y revisiones periódicas para mantener una sonrisa saludable.',
    durationMinutes: 30,
    basePrice: 80000,
    icon: 'Stethoscope',
  },
  {
    name: 'Ortodoncia',
    slug: 'ortodoncia',
    description: 'Corrección de la posición dental y mordida mediante brackets convencionales, estéticos o alineadores invisibles. Tratamientos personalizados para lograr una sonrisa alineada y funcional.',
    durationMinutes: 45,
    basePrice: 250000,
    icon: 'AlignCenter',
  },
  {
    name: 'Endodoncia',
    slug: 'endodoncia',
    description: 'Tratamiento de conductos para eliminar infecciones y salvar dientes dañados. Utilizamos tecnología avanzada de última generación para procedimientos precisos y mínimamente invasivos.',
    durationMinutes: 60,
    basePrice: 350000,
    icon: 'Target',
  },
  {
    name: 'Periodoncia',
    slug: 'periodoncia',
    description: 'Tratamiento especializado de encías y tejidos de soporte dental. Abordamos gingivitis, periodontitis y realizamos cirugías periodontales con técnicas regenerativas avanzadas.',
    durationMinutes: 45,
    basePrice: 180000,
    icon: 'Shield',
  },
  {
    name: 'Implantología',
    slug: 'implantologia',
    description: 'Reemplazo de dientes perdidos con implantes de titanio de alta gama. Cirugía guiada por computadora para resultados predecibles y una rehabilitación oral duradera y natural.',
    durationMinutes: 90,
    basePrice: 2500000,
    icon: 'Wrench',
  },
  {
    name: 'Estética Dental',
    slug: 'estetica-dental',
    description: 'Carillas de porcelana, diseño de sonrisa digital y restauraciones estéticas de alta calidad. Transformamos sonrisas con técnicas mínimamente invasivas y resultados naturales.',
    durationMinutes: 60,
    basePrice: 800000,
    icon: 'Sparkles',
  },
  {
    name: 'Blanqueamiento Dental',
    slug: 'blanqueamiento-dental',
    description: 'Blanqueamiento profesional con tecnología LED y geles de última generación. Resultados visibles desde la primera sesión con un proceso seguro y cómodo para el paciente.',
    durationMinutes: 45,
    basePrice: 450000,
    icon: 'Sun',
  },
  {
    name: 'Odontopediatría',
    slug: 'odontopediatria',
    description: 'Atención dental especializada para niños y adolescentes en un ambiente amigable y cálido. Prevención, tratamientos y educación en salud oral con un enfoque lúdico.',
    durationMinutes: 30,
    basePrice: 70000,
    icon: 'Baby',
  },
  {
    name: 'Cirugía Oral',
    slug: 'cirugia-oral',
    description: 'Extracciones complejas, cirugía de terceros molares, biopsias y procedimientos quirúrgicos avanzados. Tecnología de punta y protocolos de mínima invasión para una recuperación rápida.',
    durationMinutes: 60,
    basePrice: 500000,
    icon: 'Scissors',
  },
  {
    name: 'Rehabilitación Oral',
    slug: 'rehabilitacion-oral',
    description: 'Prótesis fijas y removibles, coronas, puentes y rehabilitación completa de la función masticatoria y estética. Devolvemos funcionalidad y confianza con materiales de primera calidad.',
    durationMinutes: 60,
    basePrice: 600000,
    icon: 'RefreshCw',
  },
];

const defaultSchedule = [
  { day: 'lunes', startTime: '08:00', endTime: '17:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
  { day: 'martes', startTime: '08:00', endTime: '17:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
  { day: 'miercoles', startTime: '08:00', endTime: '17:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
  { day: 'jueves', startTime: '08:00', endTime: '17:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
  { day: 'viernes', startTime: '08:00', endTime: '17:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
];

export const specialistsData = [
  {
    name: 'Dra. María Alejandra Rodríguez',
    slug: 'dra-maria-rodriguez',
    photo: '/images/specialist-1.jpg',
    specialty: 'Odontología General',
    subspecialty: 'Odontología Preventiva',
    description: 'Odontóloga general con más de 12 años de experiencia en diagnóstico y prevención dental. Apasionada por la educación en salud oral y el cuidado integral de sus pacientes. Certificada en odontología mínimamente invasiva.',
    experience: 12,
    servicesSlugs: ['odontologia-general', 'blanqueamiento-dental'],
    weeklySchedule: defaultSchedule,
  },
  {
    name: 'Dr. Carlos Eduardo Martínez',
    slug: 'dr-carlos-martinez',
    photo: '/images/specialist-2.jpg',
    specialty: 'Ortodoncia',
    subspecialty: 'Alineadores Invisibles',
    description: 'Especialista en ortodoncia con formación en alineadores invisibles y brackets estéticos. Más de 15 años transformando sonrisas con técnicas de vanguardia. Fellow del Board Colombiano de Ortodoncia.',
    experience: 15,
    servicesSlugs: ['ortodoncia'],
    weeklySchedule: [
      ...defaultSchedule,
      { day: 'sabado', startTime: '08:00', endTime: '13:00', blockDuration: 45, breaks: [] },
    ],
  },
  {
    name: 'Dra. Laura Valentina Gómez',
    slug: 'dra-laura-gomez',
    photo: '/images/specialist-3.jpg',
    specialty: 'Endodoncia',
    description: 'Endodoncista especializada en tratamiento de conductos con microscopia operatoria. Formación en la Universidad Javeriana y experiencia internacional en técnicas de última generación.',
    experience: 10,
    servicesSlugs: ['endodoncia'],
    weeklySchedule: [
      { day: 'lunes', startTime: '09:00', endTime: '18:00', blockDuration: 60, breaks: [{ start: '13:00', end: '14:00' }] },
      { day: 'miercoles', startTime: '09:00', endTime: '18:00', blockDuration: 60, breaks: [{ start: '13:00', end: '14:00' }] },
      { day: 'viernes', startTime: '09:00', endTime: '18:00', blockDuration: 60, breaks: [{ start: '13:00', end: '14:00' }] },
    ],
  },
  {
    name: 'Dr. Andrés Felipe Herrera',
    slug: 'dr-andres-herrera',
    photo: '/images/specialist-4.jpg',
    specialty: 'Implantología',
    subspecialty: 'Cirugía Oral',
    description: 'Cirujano oral e implantólogo con más de 18 años de experiencia. Especialista en cirugía guiada por computador e implantes de carga inmediata. Profesor universitario y conferencista internacional.',
    experience: 18,
    servicesSlugs: ['implantologia', 'cirugia-oral'],
    weeklySchedule: [
      { day: 'martes', startTime: '07:00', endTime: '16:00', blockDuration: 60, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'jueves', startTime: '07:00', endTime: '16:00', blockDuration: 60, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'sabado', startTime: '08:00', endTime: '13:00', blockDuration: 60, breaks: [] },
    ],
  },
  {
    name: 'Dra. Camila Andrea Restrepo',
    slug: 'dra-camila-restrepo',
    photo: '/images/specialist-5.jpg',
    specialty: 'Estética Dental',
    subspecialty: 'Diseño de Sonrisa',
    description: 'Especialista en estética dental y diseño de sonrisa digital. Formación en carillas cerámicas con la escuela italiana de odontología estética. Más de 500 diseños de sonrisa exitosos.',
    experience: 8,
    servicesSlugs: ['estetica-dental', 'blanqueamiento-dental', 'rehabilitacion-oral'],
    weeklySchedule: defaultSchedule,
  },
  {
    name: 'Dra. Sofía Isabel Peña',
    slug: 'dra-sofia-pena',
    photo: '/images/specialist-6.jpg',
    specialty: 'Odontopediatría',
    description: 'Odontopediatra dedicada al cuidado dental de niños y adolescentes. Su enfoque lúdico y paciente genera confianza en los más pequeños. Especialización en manejo de pacientes con necesidades especiales.',
    experience: 9,
    servicesSlugs: ['odontopediatria', 'odontologia-general'],
    weeklySchedule: [
      { day: 'lunes', startTime: '08:00', endTime: '16:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'martes', startTime: '08:00', endTime: '16:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'miercoles', startTime: '08:00', endTime: '16:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'jueves', startTime: '08:00', endTime: '16:00', blockDuration: 30, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'viernes', startTime: '08:00', endTime: '14:00', blockDuration: 30, breaks: [] },
    ],
  },
  {
    name: 'Dr. Ricardo José Vargas',
    slug: 'dr-ricardo-vargas',
    photo: '/images/specialist-7.jpg',
    specialty: 'Periodoncia',
    subspecialty: 'Regeneración Tisular',
    description: 'Periodoncista con amplia experiencia en tratamiento de enfermedad periodontal avanzada y técnicas regenerativas. Investigador activo en biomateriales dentales.',
    experience: 14,
    servicesSlugs: ['periodoncia'],
    weeklySchedule: [
      { day: 'lunes', startTime: '08:00', endTime: '17:00', blockDuration: 45, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'miercoles', startTime: '08:00', endTime: '17:00', blockDuration: 45, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'viernes', startTime: '08:00', endTime: '17:00', blockDuration: 45, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'sabado', startTime: '08:00', endTime: '12:00', blockDuration: 45, breaks: [] },
    ],
  },
  {
    name: 'Dra. Valentina Morales Castro',
    slug: 'dra-valentina-morales',
    photo: '/images/specialist-8.jpg',
    specialty: 'Rehabilitación Oral',
    description: 'Rehabilitadora oral con enfoque en prótesis fija sobre implantes y rehabilitación full arch. Formación en Alemania y experiencia en casos complejos multidisciplinarios.',
    experience: 11,
    servicesSlugs: ['rehabilitacion-oral', 'estetica-dental'],
    weeklySchedule: [
      { day: 'martes', startTime: '08:00', endTime: '17:00', blockDuration: 60, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'jueves', startTime: '08:00', endTime: '17:00', blockDuration: 60, breaks: [{ start: '12:00', end: '13:00' }] },
      { day: 'sabado', startTime: '08:00', endTime: '13:00', blockDuration: 60, breaks: [] },
    ],
  },
];

export const testimonialsData = [
  {
    id: '1',
    name: 'Ana Patricia Gutiérrez',
    treatment: 'Diseño de Sonrisa',
    rating: 5,
    comment: 'Mi experiencia fue increíble. La Dra. Restrepo diseñó mi sonrisa con un nivel de detalle que superó todas mis expectativas. El resultado es completamente natural y me ha devuelto la confianza. ¡100% recomendada!',
  },
  {
    id: '2',
    name: 'Jorge Alberto Mendoza',
    treatment: 'Implantes Dentales',
    rating: 5,
    comment: 'Después de años con temor a los implantes, el Dr. Herrera me hizo sentir completamente seguro. El procedimiento fue indoloro y la recuperación más rápida de lo esperado. Hoy como con total normalidad.',
  },
  {
    id: '3',
    name: 'Carolina Fernández Mejía',
    treatment: 'Ortodoncia Invisible',
    rating: 5,
    comment: 'El Dr. Martínez fue excepcional. Los alineadores invisibles cambiaron mi sonrisa sin que nadie se diera cuenta del tratamiento. Todo el equipo es muy profesional y atento.',
  },
  {
    id: '4',
    name: 'Roberto Carlos Sánchez',
    treatment: 'Endodoncia',
    rating: 5,
    comment: 'Tenía mucho miedo por el tratamiento de conducto, pero la Dra. Gómez fue tan cuidadosa que no sentí absolutamente nada. El consultorio es impecable y la tecnología de primer nivel.',
  },
  {
    id: '5',
    name: 'Mariana López Torres',
    treatment: 'Blanqueamiento Dental',
    rating: 5,
    comment: 'En una sola sesión logré el tono que quería. El equipo es muy profesional, las instalaciones son hermosas y el resultado habla por sí solo. Volveré para mi mantenimiento anual.',
  },
  {
    id: '6',
    name: 'Felipe Andrés Ruiz',
    treatment: 'Odontopediatría',
    rating: 5,
    comment: 'Mi hijo le tenía terror al dentista hasta que conoció a la Dra. Peña. Ahora pide ir a la cita. Su paciencia y trato con los niños es extraordinario. Como padre, estoy muy agradecido.',
  },
];
